### ISSUE TITLE
Unable to create jar using "mvn package"

### ISSUE THREAD

**Issue by arbazalam2z** [SmartBear/ready-mqtt-plugin#1]
Hi,

I am unable to generate jar from the repository. It gives me error message using command "mvn package".

log:
del1-dhp-32959:/var/test-readyapi/ready-mqtt-plugin-master/ready-mqtt-plugin-master # mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Ready! API MQTT Plugin 1.5.0
[INFO] ------------------------------------------------------------------------
Downloading: http://www.eviware.com/repository/maven2/eviware/reports/1.0/reports-1.0.pom
Downloading: http://repo1.maven.org/maven2/eviware/reports/1.0/reports-1.0.pom
[WARNING] The POM for eviware:reports:jar:1.0 is missing, no dependency information available
Downloading: http://www.eviware.com/repository/maven2/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.0.1/org.eclipse.paho.client.mqttv3-1.0.1.pom
Downloading: http://repo1.maven.org/maven2/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.0.1/org.eclipse.paho.client.mqttv3-1.0.1.pom
[WARNING] The POM for org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.0.1 is missing, no dependency information available
Downloading: http://www.eviware.com/repository/maven2/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.0.1/org.eclipse.paho.client.mqttv3-1.0.1.jar
Downloading: http://repo1.maven.org/maven2/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.0.1/org.eclipse.paho.client.mqttv3-1.0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.634 s
[INFO] Finished at: 2015-11-30T11:48:28+05:30
[INFO] Final Memory: 11M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ready-mqtt-plugin: Could not resolve dependencies for project com.smartbear:ready-mqtt-plugin:jar:1.5.0: Could not find artifact org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.0.1 in eviware (http://www.eviware.com/repository/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by Roman-Rostovtsev** [comment]
Hi, arbazalam2z!
The paho artifacts were removed from the central maven repository by some unknown reason. This led to the issue you reported. I've modified the plugin's pom so it will address to the repository on the eclipse server. Please pull the last changes and the issue should be fixed.

Please note also that you should build the plugin using the following command line:

mvn clean install assembly:single

Best regards,
Roman

**Comment by arbazalam2z** [comment]
Hi Roman-Rostovtsev,

Thanks for updating the pom with new repository of paho artifacts. Its working fine now in latest Ready API.
